config/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name = 'index.html'), name = 'index'),
    path("personagens/", PersonagemListView.as_view(), name = 'personagemList'),
    path("personagens/<int:pk>/", PersonagemDetailView.as_view(), name = 'personagemDetail'),
    path("mecanicas/", MecanicaView.as_view(), name = 'mecanicas'),
    path("glossario/", TermoView.as_view(), name = 'glossario'),
    path("mapas/", MapaView.as_view(), name = 'mapas'),
    path("patch_notes/", PatchNoteView.as_view(), name = 'patch_notes'),
    path("sobre/", TemplateView.as_view(template_name = 'sobre.html'), name = 'sobre')
]

app/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

# Create your models here.

from datetime import date

class Personagem(models.Model):

    nome = models.CharField(max_length=80, verbose_name="Nome")
    imagem = models.CharField(max_length=300, verbose_name="Imagem")
    titulo = models.CharField(max_length=80, verbose_name="Título")
    estilo = models.CharField(max_length=80, verbose_name="Estilo de luta")
    pais = models.CharField(max_length=40, verbose_name="País")
    dlc = models.BooleanField(verbose_name="É DLC?")

    class Meta:
        verbose_name = "Personagem"
        verbose_name_plural = "Personagens"

    def __str__(self):
        return f'{self.nome}'
    
class TipoMecanica(models.Model):

    nome = models.CharField(max_length=80, verbose_name="Nome")

    class Meta:
        verbose_name = "Tipo de mecânica"
        verbose_name_plural = "Tipos de mecânica"

    def __str__(self):
        return f'{self.nome}'
    
class Mecanica(models.Model):

    nome = models.CharField(max_length=80, verbose_name="Nome")
    imagem = models.CharField(max_length=300, verbose_name="Imagem")
    descricao = models.CharField(max_length=400, verbose_name="Descrição")
    tipo_de_mecanica = models.ForeignKey(TipoMecanica, on_delete=models.CASCADE, verbose_name="Tipo de mecânica")

    class Meta:
        verbose_name = "Mecânica"
        verbose_name_plural = "Mecânicas"

    def __str__(self):
        return f'{self.nome}'

class Golpe(models.Model):

    nome = models.CharField(max_length=80, verbose_name="Nome")
    estrutura = ArrayField(models.CharField(max_length=300), verbose_name="Estrutura")
    dano = models.PositiveIntegerField(verbose_name="Dano")
    frame_start = models.IntegerField(verbose_name="Frames de início")
    frame_block = models.IntegerField(verbose_name="Frames de bloqueio")
    mecanicas = models.ManyToManyField(Mecanica, verbose_name="Mecânica", blank=True)
    personagem = models.ForeignKey(Personagem, on_delete=models.CASCADE, verbose_name="Personagem")

    class Meta:
        verbose_name = "Golpe"
        verbose_name_plural = "Golpes"

    def __str__(self):
        return f'{self.nome}'
    
class DificuldadeCombo(models.Model):

    nome = models.CharField(max_length=80, verbose_name="Nome")

    class Meta:
        verbose_name = "Dificuldade do combo"
        verbose_name_plural = "Dificuldades do combo"

    def __str__(self):
        return f'{self.nome}'
    
class Combo(models.Model):

    imagem = models.CharField(max_length=300, verbose_name="Imagem")
    dano = models.PositiveIntegerField(verbose_name="Dano")
    dificuldade = models.ForeignKey(DificuldadeCombo, on_delete=models.CASCADE, verbose_name="Dificuldade")
    personagem = models.ForeignKey(Personagem, on_delete=models.CASCADE, verbose_name="Personagem")

    class Meta:
        verbose_name = "Combo"
        verbose_name_plural = "Combos"

    def __str__(self):
        return f'{self.id}'
    
class JogadorProfissional(models.Model):

    nome = models.CharField(max_length=80, verbose_name="Nome")
    youtube = models.CharField(max_length=300, verbose_name="Youtube")
    personagem = models.ForeignKey(Personagem, on_delete=models.CASCADE, verbose_name="Personagem")

    class Meta:
        verbose_name = "Jogador profissional"
        verbose_name_plural = "Jogadores profissionais"

    def __str__(self):
        return f'{self.nome}'
    
class Termo(models.Model):

    nome = models.CharField(max_length=80, verbose_name="Nome")
    descricao = models.CharField(max_length=300, verbose_name="Descrição")

    class Meta:
        verbose_name = "Termo"
        verbose_name_plural = "Termos"

    def __str__(self):
        return f'{self.nome}'
    
class Mapa(models.Model):

    nome = models.CharField(max_length=80, verbose_name="Nome")
    imagem = models.CharField(max_length=300, verbose_name="Imagem")
    mecanicas = models.ManyToManyField(Mecanica, verbose_name="Mecânica")

    class Meta:
        verbose_name = "Mapa"
        verbose_name_plural = "Mapas"

    def __str__(self):
        return f'{self.nome}'
    
class PatchNote(models.Model):

    versao = models.CharField(max_length=80, verbose_name="Versão", default="Teste")
    data = models.DateField(verbose_name="Data", default=date.today)
    link = models.CharField(max_length=300, verbose_name="Link")

    class Meta:
        verbose_name = "Patch note"
        verbose_name_plural = "Patch notes"

    def __str__(self):
        return f'{self.versao}'

app/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from .models import *

# Create your views here.

class IndexView(View):

    def get(self, request, *args, **kwargs):
        return render(request, 'index.html')
    
class PersonagemListView(ListView):

    model = Personagem
    context_object_name = "lista"
    template_name = "personagens/lista.html"

    def get_queryset(self):
        return Personagem.objects.all().order_by('id')

class PersonagemDetailView(DetailView):

    model = Personagem
    context_object_name = "detalhes"
    template_name = "personagens/detalhes.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        personagem = self.object # 1
        combos = Combo.objects.filter(personagem=personagem).order_by('dificuldade') # 2
        context['combos'] = combos # 3
        return context
    
class MecanicaView(View):

    def get(self, request, *args, **kwargs):
        mecanicas = Mecanica.objects.all()
        return render(request, 'mecanicas.html', {'mecanicas':mecanicas})

class TermoView(View):

    def get(self, request, *args, **kwargs):
        termos = Termo.objects.all().order_by("nome")
        return render(request, 'termos.html', {'termos':termos})
    
class MapaView(View):

    def get(self, request, *args, **kwargs):
        mapas = Mapa.objects.all().order_by("nome")
        return render(request, 'mapas.html', {'mapas':mapas})
    
class PatchNoteView(View):

    def get(self, request, *args, **kwargs):
        patch_notes = PatchNote.objects.all().order_by("-id")
        return render(request, 'patch_notes.html', {'patch_notes':patch_notes})
    
class SobreView(View):

    def get(self, request, *args, **kwargs):
        return render(request, 'sobre.html')

app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'css/index.css' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="icon" type="image/x-icon" href="{% static 'img/t8logo.png' %}">
    <title>TekkenHub</title>
  </head>
  <body class="vh-100 overflow-hidden">
    <video autoplay muted loop id="myVideo">
      <source src="{% static 'videos/video1.mp4' %}" type="video/mp4">
    </video>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-transparent">
      <div class="container dynamic-container">
        <!-- Logo -->
        <a class="navbar-brand fs-4"><img src="{% static 'img/t8logo.png' %}" alt="Tekken 8 Logo" width="40" height="40"></a>
        <a class="navbar-brand logo-title dynamic-font-size" href="{% url 'index' %}">
          <span class="title-color-a">Tekken</span>
          <span class="title-color-b">Hub</span>
        </a>
        <!-- Toogle Button -->
        <button class="navbar-toggler shadow-none border-0" type="button" data-bs-toggle="offcanvas"
        data-bs-target="#offcanvasNavbar"aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Sidebar -->
        <div class="sidebar offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
          <!-- Sidebar Header -->
          <div class="offcanvas-header text-white border-bottom">
            <a class="navbar-brand fs-4"><img src="{% static 'img/t8logo.png' %}" alt="Tekken 8 Logo" width="40" height="40"></a>
            <h5 class="offcanvas-title logo-title" id="offcanvasNavbarLabel">
              <span class="title-color-a">Tekken</span>
              <span class="title-color-b">Hub</span>
            </h5>
            <button type="button" class="btn-close btn-close-white shadow-none" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <!-- Sidebar Body -->
          <div class="offcanvas-body d-flex flex-column flex-lg-row p-4 p-lg-0">
            <ul class="navbar-nav justify-content-center align-items-center fs-5 flex-grow-1"> <!-- pe-3 -->
              <!-- <li class="nav-item max-2">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li> -->
              <li class="nav-item mx-2">
                <a class="nav-link" href="{% url 'personagemList' %}">Personagens</a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link" href="{% url 'mapas' %}">Mapas</a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link" href="{% url 'mecanicas' %}">Mecânicas</a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link" href="{% url 'glossario' %}">Glossário</a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link" href="{% url 'patch_notes' %}">Patch Notes</a>
              </li>
            </ul>
            <!-- About -->
            <div class="d-flex flex-column flex-lg-row align-items-center gap-3">
              <a href="{% url 'sobre' %}" class="text-white text-decoration-none px-3 py-1 rounded-4 about-button">Sobre</a>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <main>
      <section class="overlay w-100 vh-100 d-flex flex-column justify-content-center align-items-center text-white fs-1">
        <h1 class="logo-title main-logo-section">
          <span class="title-color-a">Tekken</span>
          <span class="title-color-b">Hub</span>
        </h1>
      </section>
    </main>
  </body>
</html>

app/templates/mapas.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{% static 'css/mapas.css' %}"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <link rel="icon" type="image/x-icon" href="{% static 'img/t8logo.png' %}">
        <title>TekkenHub | Mapas</title>
    </head>
    <body class="vh-100 overflow-hidden">
        {% include 'navbar.html' %}
        <main>
            <section class="overlay w-100 vh-100 d-flex flex-columnjustify-content-center align-items-center text-white fs-1" style="height: 92dvh !important;">
                <h2 class="page-title">Mapas</h2>
                <div class="main-section">
                    {% for Mapa in mapas %}
                    <div class="mapa-section">
                        <div class="img-details">
                            <img src="{{Mapa.imagem}}" alt="Map" width="240px" height="145px">
                        </div>
                        <div class="mapa-details">
                            <h3 class="title">{{Mapa.nome | upper}}</h3>
                            <div style="text-align: center;">
                                {% for mecanica in Mapa.mecanicas.all %}
                                    <img src="{{ mecanica.imagem }}" alt="{{ mecanica.nome }}" width="35px">
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endfor %} 
                </div>
            </section>
        </main>
    </body>
</html>

app/templates/mecanicas.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{% static 'css/mecanicas.css' %}"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="icon" type="image/x-icon" href="{% static 'img/t8logo.png' %}">
        <title>TekkenHub | Mecânicas</title>
    </head>
    <body class="vh-100 overflow-hidden">
        {% include 'navbar.html' %}
        <main>
            <section class="overlay w-100 vh-100 d-flex flex-columnjustify-content-center align-items-center text-white fs-1" style="height: 92dvh !important;">
                <h2 class="page-title">Mecânicas</h2>
                <div class="main-section">
                    <table class="table custom">
                        <thead>
                            <tr>
                                <th scope="col">Ícone</th>
                                <th scope="col">Nome</th>
                                <th scope="col">Categoria</th>
                                <th scope="col">Descrição</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for mecanica in mecanicas %}
                            <tr>
                                <td style="vertical-align: middle; width: 10%;"><img src="{{ mecanica.imagem }}" width="40px"></td>
                                <td style="vertical-align: middle; width: 15%;">{{ mecanica.nome }}</td>
                                <td style="vertical-align: middle; width: 15%;">{{ mecanica.tipo_de_mecanica }}</td>
                                <td style="text-align: justify; width: 60%;">{{ mecanica.descricao }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </section>
        </main>
    </body>
</html>

app/templates/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}"/>
<nav class="navbar navbar-expand-lg navbar-dark navbar-color {% if request.path == '/sobre/' %}custom-navbar-color{% endif %}">
    <div class="container dynamic-container">
        <!-- Logo -->
        <a class="navbar-brand fs-4"><img src="{% static 'img/t8logo.png' %}" alt="Tekken 8 Logo" width="40" height="40"></a>
        <a class="navbar-brand logo-title dynamic-font-size" href="{% url 'index' %}">
            <span class="title-color-a">Tekken</span>
            <span class="title-color-b">Hub</span>
        </a>
        <!-- Toogle Button -->
        <button class="navbar-toggler shadow-none border-0" type="button" data-bs-toggle="offcanvas"
        data-bs-target="#offcanvasNavbar"aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Sidebar -->
        <div class="sidebar offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <!-- Sidebar Header -->
            <div class="offcanvas-header text-white border-bottom">
                <a class="navbar-brand fs-4"><img src="{% static 'img/t8logo.png' %}" alt="Tekken 8 Logo" width="40" height="40"></a>
                <h5 class="offcanvas-title logo-title" id="offcanvasNavbarLabel">
                    <span class="title-color-a">Tekken</span>
                    <span class="title-color-b">Hub</span>
                </h5>
                <button type="button" class="btn-close btn-close-white shadow-none" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <!-- Sidebar Body -->
            <div class="offcanvas-body d-flex flex-column flex-lg-row p-4 p-lg-0">
                <ul class="navbar-nav justify-content-center align-items-center fs-5 flex-grow-1"> <!-- pe-3 -->
                    <!-- <li class="nav-item max-2">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li> -->
                    <li class="nav-item mx-2">
                        <a class="nav-link {% if request.path == '/personagens/' %}active{% endif %}" href="{% url 'personagemList' %}">Personagens</a>
                    </li>
                    <li class="nav-item mx-2">
                        <a class="nav-link {% if request.path == '/mapas/' %}active{% endif %}" href="{% url 'mapas' %}">Mapas</a>
                    </li>
                    <li class="nav-item mx-2">
                        <a class="nav-link {% if request.path == '/mecanicas/' %}active{% endif %}" href="{% url 'mecanicas' %}">Mecânicas</a>
                    </li>
                    <li class="nav-item mx-2">
                        <a class="nav-link {% if request.path == '/glossario/' %}active{% endif %}" href="{% url 'glossario' %}">Glossário</a>
                    </li>
                    <li class="nav-item mx-2">
                        <a class="nav-link {% if request.path == '/patch_notes/' %}active{% endif %}" href="{% url 'patch_notes' %}">Patch Notes</a>
                    </li>
                </ul>
                <!-- About -->
                <div class="d-flex flex-column flex-lg-row align-items-center gap-3">
                    <a href="{% url 'sobre' %}" class="text-white text-decoration-none px-3 py-1 rounded-4 about-button">Sobre</a>
                </div>
            </div>
        </div>
    </div>
</nav>

app/templates/patch_notes.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{% static 'css/patch_notes.css' %}"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="icon" type="image/x-icon" href="{% static 'img/t8logo.png' %}">
        <title>TekkenHub | Patch Notes</title>
    </head>
    <body class="vh-100 overflow-hidden">
        {% include 'navbar.html' %}
        <main>
            <section class="overlay w-100 vh-100 d-flex flex-columnjustify-content-center align-items-center text-white fs-1" style="height: 92dvh !important;">
                <h2 class="page-title">Patch Notes</h2>
                <div class="main-section">
                    <table class="table custom">
                        <thead>
                            <tr>
                                <th scope="col">Versão</th>
                                <th scope="col">Data</th>
                                <th scope="col">Link</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for patch in patch_notes %}
                            <tr>
                                <td>{{ patch.versao }}</td>
                                <td>{{ patch.data | date:"SHORT_DATE_FORMAT" }}</td>
                                <td>
                                    <a href="{{ patch.link }}" target="_blank" rel="noopener noreferrer">
                                        <i class="bi bi-box-arrow-up-right"></i>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %} 
                        </tbody>
                    </table>
                </div>
            </section>
        </main>
    </body>
</html>

app/templates/personagens/detalhes.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{% static 'css/detalhes.css' %}"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="icon" type="image/x-icon" href="{% static 'img/t8logo.png' %}">
        <title>TekkenHub | Personagens</title>
    </head>
    <body class="vh-100 overflow-hidden">
        {% include 'navbar.html' %}
        <main>
            <section class="overlay w-100 vh-100 d-flex flex-columnjustify-content-center align-items-center text-white fs-1" style="height: 92dvh !important;">
                <div class="main-section">
                    <div class="mapa-section">
                        <img src="{{ detalhes.imagem }}" width="160px">
                    </div>
                    <div class="character-summary">
                        <h2>{{ detalhes.nome }}</h2>
                        <h3 style="margin-top: 5px;">{{ detalhes.titulo }}</h3>
                        <div>
                            <div class="character-info">
                                <h5 style="margin-right: 10px; margin-bottom: 10px !important;"><span style="color: #ed1665;">Estilo:</span> {{ detalhes.estilo }}</h5>
                                <h5 style="margin-bottom: 10px !important;"><span style="color: #ed1665;">País:</span> {{ detalhes.pais }}</h5>
                            </div>
                            <h5>
                                <span style="color: #ed1665;">Tipo:</span>
                                {% if detalhes.dlc == True %} DLC {% else %} Jogo Base {% endif %}
                            </h5>
                            
                        </div>
                        <div class="players-section">
                            {% for jogador in detalhes.jogadorprofissional_set.all %}
                                <div class="{% if not forloop.last %}m-r-md{% endif %}" style="font-size: 20px;">
                                    <a class="players-link" href="{{ jogador.youtube }}" target="_blank" rel="noopener noreferrer">
                                        <i class="bi bi-youtube"></i> {{ jogador.nome }}
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="golpes-section">
                    <h2 style="align-self: center; margin-bottom: 10px;">GOLPES</h2>
                    {% for golpe in detalhes.golpe_set.all %}
                    <div class="golpe-card">
                        <div class="golpe-summary">
                            <h5 style="font-size: x-large;">{{ forloop.counter }}. {{ golpe.nome }}</h5>
                            <div>
                                {% for item in golpe.estrutura %}
                                    <img src="{{ item }}" width="60px">
                                {% endfor %}
                            </div>
                        </div>
                        <div class="golpe-info">
                            <div class="gople-mecanicas">
                                {% for item in golpe.mecanicas.all %}
                                    <img src="../{{ item.imagem }}" width="30px" class="{% if not forloop.last %}m-r-md{% endif %}">
                                {% endfor %}
                            </div>
                            <h5 style="margin-bottom: 5px !important; font-size: 16px;">
                                <span style="color: #ed1665;">Start:</span> {{ golpe.frame_start }}
                            </h5>
                            <h5 style="margin-bottom: 5px !important; font-size: 16px;">
                                <span style="color: #ed1665;">Block:</span> {{ golpe.frame_block }}
                            </h5>
                            <h5 style="margin-bottom: 0px !important; font-size: 16px;">
                                <span style="color: #ed1665;">Dano:</span> {{ golpe.dano }}
                            </h5>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="golpes-section">
                    <h2 style="align-self: center; margin-bottom: 10px;">COMBOS</h2>
                    <!-- for combo in detalhes.combo_set.all -->
                    {% for combo in combos %}
                    <div class="golpe-card">
                        <div class="golpe-summary">
                            <h5 style="font-size: x-large;">{{ forloop.counter }}. {{ combo.dificuldade }} - Dano: {{ combo.dano }}</h5>
                            <div>
                                <img src="{{ combo.imagem }}" width="95%">
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </section>
        </main>
    </body>
</html>